blog/apps/noticias/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'noticias'

urlpatterns = [
    path('', views.ListarNoticias, name='listar'),
    path('listarNoticia/', views.mostrarNoticia.as_view()), #clase
    path('detalle/<int:pk>', views.DetalleNoticias, name='detalle'),
    path('addNoticia', views.AddNoticia, name='addnoticia'),
    path('noticias/<int:pk>/edit/', views.EditNoticia, name='edit_noticia'),
    #url comentarios
    path('comment/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('comment/add/<int:noticia_id>/', views.add_comment, name='add_comment'),
    path('comment/edit/<int:comment_id>/', views.edit_comment, name='edit_comment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #1er parametro: es el texto de la url
    #2do parametro: es la vista que se va a ejecutar
    #3er parametro: es el nombre de la url
    path('', views.Home, name='home'),
    path('nosotros/', views.Nosotros, name='nosotros'),
    path('cocina/', views.Cocina, name='cocina'),

    #urls aplicaciones
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
   <title>Degustando Sabores > {% block titulo %}{% endblock titulo %}</title>
</head>
<body class="contenedor"> 
   <div> 
      <img src="{% static 'img/logo.jpg' %}" width="810px" height="90px">
      <ol>
         <a href="{% url 'home' %}">Home</a>   
         <a href="{% url 'nosotros' %}">Bio del Blog</a>
         <a href="{% url 'cocina' %}">Tips de Cocina</a>
         <a href="{% url 'noticias:listar' %}">Ir a Recetas</a>

         {% if user.is_authenticated %}
         <strong>Hola {{ user.username }}</strong>
         <a href="{% url 'logout' %}">LOGOUT</a>
         {% else %}
         <a href="{% url 'login' %}">LOGIN</a>
         <a href="{% url 'registro' %}">REGISTRO</a>
         {% endif %}

      </ol>

   </div>
   {% block contenido %}
   {% endblock contenido %}
</body>
<footer>
   <p>
      <h3>Copyright 2023 @infoproyecto/c6-g2</h3>
   </p>
 </footer>
</html>

blog/templates/cocina.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Tips de Cocina{% endblock titulo %}

{% block contenido %}
   <h1>10 Consejos Esenciales para Mejorar tus Habilidades en la Cocina</h1>
   <p>¡Bienvenidos a nuestro espacio culinario! Aquí encontrarás una selección de consejos y trucos para elevar tus habilidades en la cocina y convertirte en un maestro de los fogones. Desde recetas básicas hasta técnicas más avanzadas, estos consejos te ayudarán a perfeccionar tus platos y a disfrutar aún más de la experiencia culinaria. ¡Empecemos!</p>
   <ol>
      <li><strong>Organización es clave:</strong> Antes de comenzar a cocinar, asegúrate de tener todos los ingredientes y utensilios necesarios a mano. Una cocina organizada te permitirá trabajar de manera más eficiente y evitará que olvides algún paso importante en la receta.</li>
      <li><strong>Domina el arte del cuchillo:</strong> Aprende diferentes técnicas de corte para maximizar la eficiencia en la cocina y obtener resultados profesionales. Un buen cuchillo afilado es tu mejor aliado en la preparación de ingredientes frescos.</li>
      <li><strong>Controla las temperaturas:</strong> Ya sea que estés asando, horneando o cocinando a fuego lento, asegúrate de controlar las temperaturas de cocción. Un termómetro de cocina es una herramienta útil para lograr platos perfectamente cocidos.</li>
      <li><strong>Experimenta con hierbas y especias:</strong> Las hierbas frescas y las especias pueden transformar por completo el sabor de tus platos. Anímate a probar diferentes combinaciones y descubre cómo realzan los sabores de tus recetas favoritas.</li>
      <li><strong>Aprende las técnicas básicas de cocina:</strong> Conocer métodos como saltear, cocinar al vapor, freír y asar te permitirá preparar una amplia variedad de platos con confianza.</li>
      <li><strong>No tengas miedo de probar nuevas recetas:</strong> Atrévete a salir de tu zona de confort culinaria y prueba recetas nuevas. Cocinar platos de diferentes culturas te ayudará a ampliar tus habilidades y a descubrir nuevos sabores.</li>
      <li><strong>Sigue las proporciones en las recetas:</strong> En la cocina, especialmente en la repostería, las proporciones son fundamentales. Respeta las cantidades indicadas en las recetas para obtener resultados consistentes y deliciosos.</li>
      <li><strong>Aprende a improvisar:</strong> Si te falta algún ingrediente, aprende a sustituirlo de manera adecuada. La improvisación es una habilidad valiosa en la cocina y te permitirá adaptarte a diferentes situaciones.</li>
      <li><strong>Presta atención a la presentación:</strong> Un plato bien presentado es mucho más apetecible. Aprende técnicas sencillas de decoración para darle un toque profesional a tus creaciones.</li>
      <li><strong>Practica y disfruta:</strong> La cocina es un arte que mejora con la práctica constante. No te desanimes si algo no sale como esperabas en un principio. Disfruta el proceso y aprende de cada experiencia culinaria.</li>
   </ol>
   <p>Recuerda que la cocina es una forma de expresión creativa, así que diviértete mientras cocinas y comparte tus creaciones con amigos y familiares. ¡Buen provecho!</p>
{% endblock contenido %}

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Home{% endblock titulo %}

{% block contenido %}
    <header>
      <h1>¡Bienvenidos a Degustando Sabores!</h1>
      <p class="subtitle">Aquí, te sumergirás en un mundo culinario lleno de sabores, colores y aromas que despertarán tus sentidos.</p>
      <p class="subtitle">Nuestro blog está dedicado a todos los amantes de la cocina, desde principiantes entusiastas hasta chefs experimentados.</p>
      <p class="subtitle">Te brindaremos recetas exquisitas, consejos útiles, técnicas culinarias y mucho más para que puedas deleitar a tus seres queridos con deliciosos platillos y crear momentos inolvidables alrededor de la mesa.</p>
    </header>
    <main>
      <section>
        <h2>Recetas recientes</h2>
        <ul>
          <li><a href="#">Locro</a></li>
          <li><a href="#">Empanadas fritas</a></li>
          <li><a href="#">Postre de chocolate</a></li>
        </ul>
      </section>
      <section>
        <h2>Próximas recetas</h2>
        <ul>
          <li><a href="#">Torta de chocolate</a></li>
          <li><a href="#">Helado de vainilla</a></li>
          <li><a href="#">Galletas con frutos secos</a></li>
        </ul>
      </section>
    </main>
  </main>
{% endblock contenido %}

blog/templates/nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Bio del Blog{% endblock titulo %}

{% block contenido %}
   <header>
      <h1>Presentamos aquí a los creadores de "Degustando Sabores"</h1>
      <p class="subtitle">Chef Orlando: Dedicado a la cocina desde el año 2012, ha recorrido los restaurantes más populares del mundo.</p>
      <p class="subtitle">Chef Matias: Un apasionado cocinero de los lugares de comidas más visitados por el turismo extranjero en la Argentina.</p>
    </header>
{% endblock contenido %}