blog/apps/noticias/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'noticias'

urlpatterns = [
    path('', views.ListarNoticias, name='listar'),
    path('listarNoticia/', views.mostrarNoticia.as_view()), #clase
    path('detalle/<int:pk>', views.DetalleNoticias, name='detalle'),
    path('addNoticia', views.AddNoticia, name='addnoticia'),
    path('noticias/<int:pk>/edit/', views.EditNoticia, name='edit_noticia'),
    #url comentarios
    path('comment/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('comment/add/<int:noticia_id>/', views.add_comment, name='add_comment'),
    path('comment/edit/<int:comment_id>/', views.edit_comment, name='edit_comment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #1er parametro: es el texto de la url
    #2do parametro: es la vista que se va a ejecutar
    #3er parametro: es el nombre de la url
    path('', views.Home, name='home'),
    path('nosotros/', views.Nosotros, name='nosotros'),
    path('cocina/', views.Cocina, name='cocina'),

    #urls aplicaciones
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/noticias/models.py
from django.db import models
from apps.usuarios.models import Usuario

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nombre


class Noticia(models.Model):
    titulo = models.CharField(max_length=250)
    resumen = models.CharField(max_length=100)
    contenido = models.TextField()
    fecha_de_publicacion = models.DateTimeField(auto_now_add=True)
    #para imagen debemos instalar pillow
    imagen = models.ImageField(upload_to= 'noticias')
    categoria_noticia = models.ForeignKey(Categoria, on_delete= models.CASCADE) #SET_NULL
    #author = models.ForeignKey(Usuario, default=Usuario.objects.get(is_superuser=True).pk, on_delete=models.CASCADE) (No! No!)
    author = models.ForeignKey(Usuario, default=Usuario.objects.filter(is_superuser=True).first(), on_delete=models.CASCADE)


    def __str__(self):
        return self.titulo
    
class Comment(models.Model):
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=100)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

blog/apps/noticias/forms.py
from django import forms
from .models import Noticia, Comment

class NoticiaForm(forms.ModelForm):
    
    class Meta:
        model = Noticia
        fields = ['titulo', 'resumen', 'contenido', 'imagen', 'categoria_noticia']

# CREAR COMENTARIOS
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text'] #campos de mi formulario
        exclude = ['author']
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(CommentForm, self).__init__(*args, **kwargs)
        if user:
            self.instance.author = user.username

blog/apps/noticias/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Noticia, Categoria, Comment, Usuario
from django.views.generic.list import ListView #para las vistas clases
from .forms import NoticiaForm, CommentForm
from django.http import HttpResponseForbidden
from django.contrib import messages

# Create your views here.

#VISTA CON FUNCIONES
'''def ListarNoticias(request):
    contexto = {} #diccionario
    id_categoria = request.GET.get("id", None)

    if id_categoria:
        n = Noticia.objects.filter(categoria_noticia = id_categoria)
    else:
        n = Noticia.objects.all() #SELECT * FROM Noticias / lista objetos

    contexto['noticias'] = n

    cat = Categoria.objects.all().order_by('nombre') #ordena por nombre
    contexto['categorias'] = cat

    return render(request, 'noticias/listar.html', contexto)'''

def ListarNoticias(request):
    noticias = Noticia.objects.all()

    # Filtrar por categoría
    categoria = request.GET.get('categoria')
    if categoria:
        noticias = noticias.filter(categoria_noticia=categoria)

    # Filtrar por antigüedad ascendente
    antiguedad_asc = request.GET.get('antiguedad_asc')
    if antiguedad_asc:
        noticias = noticias.order_by('fecha_de_publicacion')

    # Filtrar por antigüedad descendente
    antiguedad_desc = request.GET.get('antiguedad_desc')
    if antiguedad_desc:
        noticias = noticias.order_by('-fecha_de_publicacion')

    # Filtrar por orden alfabético ascendente
    orden_asc = request.GET.get('orden_asc')
    if orden_asc:
        noticias = noticias.order_by('titulo')

    # Filtrar por orden alfabético descendente
    orden_desc = request.GET.get('orden_desc')
    if orden_desc:
        noticias = noticias.order_by('-titulo')

    context = {
        'noticias': noticias,
        'categorias': Categoria.objects.all(),  # Asegúrate de tener el modelo 'Categoria' importado y definido
    }
    return render(request, 'noticias/listar.html', context)


#VISTA CON CLASES
class mostrarNoticia(ListView):
    model = Noticia
    template_name = 'noticias/listarNoticia.html'

'''def DetalleNoticias(request, pk):
    contexto = {} #diccionario

    n = Noticia.objects.get(pk = pk) # 1 solo objeto

    contexto['noticia'] = n

    return render(request, 'noticias/detalle.html', contexto)
'''

def DetalleNoticias(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)
    comments = noticia.comments.all()

    #BORRAR NOTICIA
    if request.method == 'POST' and 'delete_noticia' in request.POST:
        noticia.delete()
        return redirect('noticias:listar')

    # COMENTARIO
    if request.method == 'POST' and 'add_comment' in request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.noticia = noticia
            comment.author = request.user
            comment.save()
            return redirect('noticias:detalle', pk=pk)
    else:
        form = CommentForm()

    context = {
        'noticia': noticia,
        'comments': comments,
        'form': form,
    }
    return render(request, 'noticias/detalle.html', context)
# BORRAR COMENTARIOS
@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.author or comment.staff == request.user.username:
        comment.delete()
    return redirect('noticias:detalle', pk=comment.noticia.pk)

# AÑADIR COMENTARIOS
@login_required
def add_comment(request, noticia_id):
    noticia = get_object_or_404(Noticia, id=noticia_id)
    if request.method == 'POST':
        text = request.POST.get('text')
        author = request.user.username
        # creacion de comentario
        Comment.objects.create(noticia=noticia, author=author, text=text)
    return redirect('noticias:detalle', pk=noticia_id)


# EDITAR COMENTARIOS
@login_required
def edit_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    #mensaje de error si no sos el autor
    #if comment.author != request.user.username:
        #messages.error(request, 'No tienes permisos para editar este comentario.')
        #return redirect('noticias:detalle', pk=comment.noticia.pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('noticias:detalle', pk=comment.noticia.pk)
    else:
        form = CommentForm(instance=comment)

    context = {
        'form': form,
        'comment': comment,
    }
    return render(request, 'noticias/edit_comment.html', context)

@login_required
def AddNoticia(request):
    if request.method == 'POST':
        form = NoticiaForm(request.POST, request.FILES) ##REQUEST FILE PARA LAS IMAGENES
        if form.is_valid():
            noticia = form.save(commit=False)
            noticia.author = request.user #autor de la noticia
            noticia.save()
            return redirect('home')
    else:
        form = NoticiaForm()
    
    return render(request, 'noticias/addNoticia.html', {'form': form})

@login_required
def EditNoticia(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)

    # Solo el autor puede editar la noticia
    #if noticia.author != request.user:
        #return HttpResponseForbidden("No tenes permiso para editar esta noticia.")

    if request.method == 'POST':
        form = NoticiaForm(request.POST, request.FILES, instance=noticia)
        if form.is_valid():
            form.save()
            return redirect('noticias:detalle', pk=pk)
    else:
        form = NoticiaForm(instance=noticia)

    context = {
        'form': form,
    }
    return render(request, 'noticias/editNoticia.html', context)

blog/templates/noticias/addNoticia.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Recetas{% endblock titulo %}

{% block contenido %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form action="" method="POST" enctype="multipart/form-data" class="form-group m-4">
                    <h2>Crea una noticia</h2>
                    <div class="mb-3">
                        {% csrf_token %}
                    
                        {{ form.as_p }}
                    </div>
                    
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock contenido %}

blog/templates/noticias/addNoticiaDesglosado.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Recetas{% endblock titulo %}

{% block contenido %}
    <h2>Crea una noticia</h2>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <p>
            <label for="{{ form.titulo.id_for_label }}">Titulo:</label>
            {{ form.titulo }}
        </p>
        
        <p>
            <label for="{{ form.resumen.id_for_label }}">Resumen:</label>
            {{ form.resumen }}
        </p>
        
        <p>
            <label for="{{ form.contenido.id_for_label }}">Contenido:</label>
            {{ form.contenido }}
        </p>
        
        <p>
            <label for="{{ form.imagen.id_for_label }}">Imagen:</label>
            {{ form.imagen }}
        </p>
        
        <p>
            <label for="{{ form.categoria_noticia.id_for_label }}">Categoria noticia:</label>
            <select name="{{ form.categoria_noticia.name }}" required id="{{ form.categoria_noticia.id_for_label }}">
                {% for choice in form.categoria_noticia.field.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </p>
        
        <button type="submit">Guardar</button>
    </form>
{% endblock contenido %}

blog/templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
    <h2>Mi receta detallada</h2>
    {% if user.is_authenticated and noticia.author == user or user.is_staff or user.is_superuser %}
        <a href="{% url 'noticias:edit_noticia' pk=noticia.pk %}">Editar</a>

        <form method="POST" action="{% url 'noticias:detalle' pk=noticia.pk %}">
            {% csrf_token %}
            <button type="submit" name="delete_noticia">BORRAR</button>
        </form>
    {% endif %}
    <img src="{{ noticia.imagen.url }}" width="50%">
    <p>TITULO: {{ noticia.titulo }}</p>
    <p>FECHA: {{ noticia.fecha_de_publicacion }}</p>
    <p>AUTOR: {{ noticia.author }}</p>
    <p>CATEGORIA: {{ noticia.categoria_noticia }}</p>
    <p>CUERPO: {{ noticia.contenido }}</p>
    <br>

    <h3>Comentarios</h3>
    {% for comment in comments %}
        <!-- <img src="{{user.imagen.url}}" style="height: 2rem; border-radius: 10%;"></img>}} -->
        <p>{{ comment.author }}</p>
        <p>{{ comment.text }}</p>
        <p>{{ comment.created_at }}</p>
        <form method="POST" action="{% url 'noticias:delete_comment' comment.id %}">
            {% csrf_token %}
            {% if comment.author == user.username or user.is_staff or user.is_superuser %}
                <button type="submit">Borrar comentario</button>
                <a href="{% url 'noticias:edit_comment' comment_id=comment.id %}">Editar comentario</a>
            {% endif %}
        </form>
        <hr>
    {% empty %}
        <p>No hay comentarios.</p>
    {% endfor %}

    {% if user.is_authenticated %}
        <h3>Añadir Comentario</h3>
        <form method="POST" action="{% url 'noticias:add_comment' noticia.pk %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Enviar</button>
        </form>
    {% else %}
        <p>Debe iniciar sesión para añadir un comentario</p>
        <a href="{% url 'login' %}">LOGIN</a>
    {% endif %}

    <br><br>
    <a href="{% url 'noticias:listar' %}">VOLVER</a>
{% endblock contenido %}

blog/templates/noticias/editNoticia.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Editar Receta{% endblock titulo %}

{% block contenido %}
    <h2>Edita la noticia</h2>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
{% endblock contenido %}

blog/templates/noticias/edit_comment.html
{% extends 'base.html' %}
{% block contenido %}
    <h2>Editar Comentario</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock contenido %}

blog/templates/noticias/listar.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Recetas{% endblock titulo %}

{% block contenido %}
    <h2>Acá están mis recetas!</h2>
    <div class="submenu">
        <div class="dropdown">
            <button class="dropdown-btn">Categorías</button>
            <div class="dropdown-content">
                <br>
                <a href="{% url 'noticias:listar' %}">Todas las recetas</a>
                {% for cat in categorias %}
                <a href="?categoria={{ cat.pk }}">{{ cat.nombre }}</a>
                {% endfor %}
                <br>
            </div>
        </div>
    </div>
    <!-- Agregar espacio y un párrafo después del bloque de categorías -->
    <p>&nbsp;</p>
    <div class="dropdown">
        <button class="dropdown-btn">Ordenar</button>
        <br>
        <div class="dropdown-content">
            <br>
            <a href="?antiguedad_asc=1">Más antiguas primero</a>
            <a href="?antiguedad_desc=1">Más recientes primero</a>
            <a href="?orden_asc=1">Orden alfabético ascendente</a>
            <a href="?orden_desc=1">Orden alfabético descendente</a>
        </div>
        <br>
    </div>
    <a href="?antiguedad_asc=1">
        <button class="arrow-btn">&#11014;</button>
    </a>
    <a href="?antiguedad_desc=1">
        <button class="arrow-btn">&#11015;</button>
    </a>
    <!-- Agregar espacio y un párrafo después del bloque de menú -->
    <br>
    <p>&nbsp;</p>
    {% if noticias %}
        {% for noti in noticias %}
            <img src="{{ noti.imagen.url }}" width="50">
            <p><a href="{% url 'noticias:detalle' noti.pk %}">TITULO: {{ noti.titulo }}</a></p>
            <p>FECHA: {{ noti.fecha_de_publicacion }}</p>
            <p>CATEGORIA: {{ noti.categoria_noticia }}</p>
            <p>CONTENIDO: {{ noti.contenido }}</p>
            <!-- Agregar espacio y un párrafo para separar cada receta -->
            <br>
            <p>&nbsp;</p>
        {% endfor %}
    {% else %}
        <h2>No hay recetas</h2>
    {% endif %}
    <!-- Agregar espacio y un párrafo después del mensaje "No hay recetas" -->
    <br>
    <p>&nbsp;</p>
{% endblock contenido %}

blog/templates/noticias/listarNoticia.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}
    {% if object_list %}
                    
        {% for p in object_list %}

        <h1>{{p.titulo}}</h1>
        {{p.contenido|safe}}
        <p>{{p.fecha_de_publicacion}}</p>

        {% endfor %}

    {% else %}
        <h1>no hay recetas :)</h1>
    {% endif %}
{% endblock contenido %}